/** Chữ riêng của video quảng bá (chữ trong game lấy từ src/i18n.ts). */
export const COPY = {
  vi: {
    hook: 'Công viên toàn\ncặp đôi…', fa: '…còn bạn\nthì FA.', hehe: 'HEHE',
    logo: 'Ném Cứt\nPhá Đám', slamTag: 'Game phá đám vô tri nhất công viên',
    weapon: 'VŨ KHÍ\nBÍ MẬT', ammo: ['Vàng ×2', 'Cầu vồng', 'Bom', 'Nam châm', 'Siêu tốc'],
    pull: 'KÉO', throw: 'NÉM', splat: 'SPLAT!',
    timing: 'CANH ĐÚNG\nKHOẢNH KHẮC',
    cast: '6 KIỂU\nCẶP ĐÔI', castNames: ['Sinh viên', 'Trà sữa', 'Selfie', 'Tỏ tình', 'Cầu hôn', 'Ông bà'], dontThrow: 'ĐỪNG NÉM!',
    combo: 'NÉM LIÊN TỤC\nĐIỂM NHÂN ĐÔI',
    bomb: 'CỤC BOM:\nBÙM CẢ ĐÁM!',
    dog: 'CẢ CHÓ CŨNG\nPHÁ ĐÁM BẠN',
    elders: 'ÔNG BÀ THÌ…\nĐỪNG!',
    dodge: 'HỌ BIẾT NÉ…', slipper: '…VÀ NÉM DÉP!', duck: 'NÚP KỊP!',
    proposal: 'CẦU HÔN?\nPHÁ LUÔN!',
    danger: 'ĐỪNG ĐỂ\nBẢO VỆ TÓM!', hold: 'GIỮ NÚP!',
    orNot: '…HOẶC KHÔNG.', caught: 'BỊ BẮT!',
    levels: '10 MÀN CHƠI', levelCards: ['Màn 1–3\nBuổi sáng', 'Màn 4–6\nHoàng hôn', 'Màn 7–9\nBan đêm', 'Boss\nPháo hoa'],
    bossIntro: 'BOSS CUỐI', bossName: 'Cặp Đôi Hạnh Phúc Nhất Công Viên',
    shields: '3 LỚP\nLÁ CHẮN', bossWin: 'BẠN THẮNG.\nNHƯNG HỌ VẪN YÊU NHAU.',
    tagline: 'Phá đám tình yêu chưa bao giờ vui thế',
    features: ['10 màn', '6 loại Cục', '6 bộ đồ', '1 boss'],
    skins: '6 BỘ ĐỒ\nPHÁ ĐÁM', skinsSub: 'Mở khóa bằng điểm chơi, không nạp tiền', perkNinja: 'NÚP NHANH +30%', perkUncle: 'NGẮM XA +10%',
    unlessCat: '…TRỪ KHI\nCÓ MÈO.', catSave: 'MÈO GHEN TỊ\nCỨU BẠN!',
    cta: 'CHƠI NGAY', footer: 'Miễn phí · Không cần cài đặt · Chơi trên điện thoại',
  },
  en: {
    hook: 'The park is full\nof lovebirds…', fa: '…and you’re\nforever alone.', hehe: 'HEHE',
    logo: 'FA\nStrike', slamTag: 'The silliest party-pooper game in the park',
    weapon: 'SECRET\nWEAPON', ammo: ['Gold ×2', 'Rainbow', 'Bomb', 'Magnet', 'Turbo'],
    pull: 'PULL', throw: 'THROW', splat: 'SPLAT!',
    timing: 'TIME IT\nRIGHT',
    cast: '6 KINDS OF\nLOVEBIRDS', castNames: ['Students', 'Bubble tea', 'Selfie', 'Confession', 'Proposal', 'Grandparents'], dontThrow: 'DON’T!',
    combo: 'KEEP HITTING\nDOUBLE POINTS',
    bomb: 'POOP BOMB:\nBOOM, EVERYONE!',
    dog: 'EVEN THE DOG\nSTEALS YOUR SHOT',
    elders: 'GRANDPARENTS?\nDON’T!',
    dodge: 'THEY DODGE…', slipper: '…AND THROW SLIPPERS!', duck: 'DUCK!',
    proposal: 'A PROPOSAL?\nRUIN IT!',
    danger: 'DON’T GET\nCAUGHT!', hold: 'HOLD HIDE!',
    orNot: '…OR NOT.', caught: 'CAUGHT!',
    levels: '10 LEVELS', levelCards: ['Levels 1–3\nMorning', 'Levels 4–6\nSunset', 'Levels 7–9\nNight', 'Boss\nFireworks'],
    bossIntro: 'FINAL BOSS', bossName: 'The Happiest Couple in the Park',
    shields: '3 LOVE\nSHIELDS', bossWin: 'YOU WON.\nBUT THEY’RE STILL IN LOVE.',
    tagline: 'Breaking hearts has never been this fun',
    features: ['10 levels', '6 poop types', '6 outfits', '1 boss'],
    skins: '6 OUTFITS TO\nPARTY-POOP IN', skinsSub: 'Unlocked by playing, never by paying', perkNinja: 'HIDE 30% FASTER', perkUncle: 'AIM +10% LONGER',
    unlessCat: '…UNLESS YOU\nHAVE A CAT.', catSave: 'JEALOUS CAT\nTO THE RESCUE!',
    cta: 'PLAY NOW', footer: 'Free · No download · Plays on your phone',
  },
};
